// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxbdbxypsldmeawwsmde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4YmRieHlwc2xkbWVhd3dzbWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODQ3MjksImV4cCI6MjA2NTU2MDcyOX0.-3Qw9A727WfOVfb_-sUU-0ryl-LNE6Y5okYdU3KJWT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);